language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "docker-compose version"
  - docker-compose --version

script:
  - docker --version # print the version for logging
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f udagram-deployment/docker/docker-compose-build.yaml push
